# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zguo/MyData/Research/3-CodeProject/EOS_H2ONaCl/desktop

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zguo/MyData/Research/3-CodeProject/EOS_H2ONaCl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zguo/MyData/Research/3-CodeProject/EOS_H2ONaCl/CMakeFiles /Users/zguo/MyData/Research/3-CodeProject/EOS_H2ONaCl/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zguo/MyData/Research/3-CodeProject/EOS_H2ONaCl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named swEOS

# Build rule for target.
swEOS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 swEOS
.PHONY : swEOS

# fast build rule for target.
swEOS/fast:
	$(MAKE) -f CMakeFiles/swEOS.dir/build.make CMakeFiles/swEOS.dir/build
.PHONY : swEOS/fast

#=============================================================================
# Target rules for targets named swEOS_autogen

# Build rule for target.
swEOS_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 swEOS_autogen
.PHONY : swEOS_autogen

# fast build rule for target.
swEOS_autogen/fast:
	$(MAKE) -f CMakeFiles/swEOS_autogen.dir/build.make CMakeFiles/swEOS_autogen.dir/build
.PHONY : swEOS_autogen/fast

MainWindow.o: MainWindow.cxx.o

.PHONY : MainWindow.o

# target to build an object file
MainWindow.cxx.o:
	$(MAKE) -f CMakeFiles/swEOS.dir/build.make CMakeFiles/swEOS.dir/MainWindow.cxx.o
.PHONY : MainWindow.cxx.o

MainWindow.i: MainWindow.cxx.i

.PHONY : MainWindow.i

# target to preprocess a source file
MainWindow.cxx.i:
	$(MAKE) -f CMakeFiles/swEOS.dir/build.make CMakeFiles/swEOS.dir/MainWindow.cxx.i
.PHONY : MainWindow.cxx.i

MainWindow.s: MainWindow.cxx.s

.PHONY : MainWindow.s

# target to generate assembly for a file
MainWindow.cxx.s:
	$(MAKE) -f CMakeFiles/swEOS.dir/build.make CMakeFiles/swEOS.dir/MainWindow.cxx.s
.PHONY : MainWindow.cxx.s

main.o: main.cxx.o

.PHONY : main.o

# target to build an object file
main.cxx.o:
	$(MAKE) -f CMakeFiles/swEOS.dir/build.make CMakeFiles/swEOS.dir/main.cxx.o
.PHONY : main.cxx.o

main.i: main.cxx.i

.PHONY : main.i

# target to preprocess a source file
main.cxx.i:
	$(MAKE) -f CMakeFiles/swEOS.dir/build.make CMakeFiles/swEOS.dir/main.cxx.i
.PHONY : main.cxx.i

main.s: main.cxx.s

.PHONY : main.s

# target to generate assembly for a file
main.cxx.s:
	$(MAKE) -f CMakeFiles/swEOS.dir/build.make CMakeFiles/swEOS.dir/main.cxx.s
.PHONY : main.cxx.s

qrc_icons.o: qrc_icons.cpp.o

.PHONY : qrc_icons.o

# target to build an object file
qrc_icons.cpp.o:
	$(MAKE) -f CMakeFiles/swEOS.dir/build.make CMakeFiles/swEOS.dir/qrc_icons.cpp.o
.PHONY : qrc_icons.cpp.o

qrc_icons.i: qrc_icons.cpp.i

.PHONY : qrc_icons.i

# target to preprocess a source file
qrc_icons.cpp.i:
	$(MAKE) -f CMakeFiles/swEOS.dir/build.make CMakeFiles/swEOS.dir/qrc_icons.cpp.i
.PHONY : qrc_icons.cpp.i

qrc_icons.s: qrc_icons.cpp.s

.PHONY : qrc_icons.s

# target to generate assembly for a file
qrc_icons.cpp.s:
	$(MAKE) -f CMakeFiles/swEOS.dir/build.make CMakeFiles/swEOS.dir/qrc_icons.cpp.s
.PHONY : qrc_icons.cpp.s

swEOS_autogen/mocs_compilation.o: swEOS_autogen/mocs_compilation.cpp.o

.PHONY : swEOS_autogen/mocs_compilation.o

# target to build an object file
swEOS_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/swEOS.dir/build.make CMakeFiles/swEOS.dir/swEOS_autogen/mocs_compilation.cpp.o
.PHONY : swEOS_autogen/mocs_compilation.cpp.o

swEOS_autogen/mocs_compilation.i: swEOS_autogen/mocs_compilation.cpp.i

.PHONY : swEOS_autogen/mocs_compilation.i

# target to preprocess a source file
swEOS_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/swEOS.dir/build.make CMakeFiles/swEOS.dir/swEOS_autogen/mocs_compilation.cpp.i
.PHONY : swEOS_autogen/mocs_compilation.cpp.i

swEOS_autogen/mocs_compilation.s: swEOS_autogen/mocs_compilation.cpp.s

.PHONY : swEOS_autogen/mocs_compilation.s

# target to generate assembly for a file
swEOS_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/swEOS.dir/build.make CMakeFiles/swEOS.dir/swEOS_autogen/mocs_compilation.cpp.s
.PHONY : swEOS_autogen/mocs_compilation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... swEOS"
	@echo "... swEOS_autogen"
	@echo "... MainWindow.o"
	@echo "... MainWindow.i"
	@echo "... MainWindow.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... qrc_icons.o"
	@echo "... qrc_icons.i"
	@echo "... qrc_icons.s"
	@echo "... swEOS_autogen/mocs_compilation.o"
	@echo "... swEOS_autogen/mocs_compilation.i"
	@echo "... swEOS_autogen/mocs_compilation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

