name: website

on: 
  push:
    branches: master

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install tools
        run: |
          pip3 install sphinx
          pip3 install sphinxcontrib-bibtex
          pip3 install sphinx-intl sphinx_inline_tabs 
          # # brew install doxygen
          # # brew install graphviz
          # brew install --cask mactex-no-gui
          # eval "$(/usr/libexec/path_helper)"
          
      - name: Generate sphinx and doxygen pages
        run: |
          cd manual/sphinx
          make html
          # make latex
          # cd build/latex/zh && make && cd ../../../
          # cd build/latex/en && make && cd ../../../
          # cd cd ../../
          # cp -rf manual/sphinx/build/html/* public
          # mkdir -p pdfs/zh && mkdir -p pdfs/en
          # cp manual/sphinx/build/latex/en/*.pdf public/pdfs/en
          # cp manual/sphinx/build/latex/zh/*.pdf public/pdfs/zh
          
      - name: install oh my zsh
        run: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      # - name: Deploy to GitHub Pages
      #   if: success()
      #   uses: crazy-max/ghaction-github-pages@v2
      #   with:
      #     target_branch: gh-pages
      #     build_dir: public
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}